### ISSUE TITLE
Memory leak in ktlintFormat task

### ISSUE THREAD

**Issue by BraisGabin** [JLLeitschuh/ktlint-gradle#507] opened 2021-07-02 07:40 UTC
Probably related with #447

I'm running `git rebase -i develop --exec "./gradlew ktlintFormat"` on a branch with 40 commits and I'm getting this error on my local machine (macOS):

```
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
   > Java heap space
```

It seems like a leak to me. The first 5 coomits ok, then the next failed. I reran the task manually on that commit and it worked. But then the 8th commit failed. and the pattern continued until the commit 15th. I can't run the task any more. It fails every single time with the error I pasted above. As soon as I killed the daemon `./gradlew --stop` it worked.

I'm using v10.1.0

**Comment by Tapchicoma** [comment] 2021-07-02 19:25
Yes, for some unknown reason (Kotlin update) Ktlint 0.41.0 uses more memory then before...

**Comment by Tapchicoma** [comment] 2021-08-09 19:47
@BraisGabin do you see similar behaviour with KtLint `0.42.1`?

**Comment by BraisGabin** [comment] 2021-08-10 09:49
Yes, same behaviour. I'm using this to reproduce it:

```shell
for run in {1..20}; do ./gradlew ktlintFormat --rerun-tasks; done
```

And after some runs I get this type of outputs:

```
Expiring Daemon because JVM heap space is exhausted
Daemon will be stopped at the end of the build after running out of JVM memory
Expiring Daemon because JVM heap space is exhausted
...
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
Expiring Daemon because JVM heap space is exhausted
```

**Comment by gabrielittner** [comment] 2021-08-10 12:27
I'm also still seeing this

**Comment by svinouze** [comment] 2021-08-10 14:20
I know it doesn't solve the issue, but you can still increase the heap size as described in the README since the default heap is 256 mb.
```
tasks.withType<org.jlleitschuh.gradle.ktlint.tasks.BaseKtLintCheckTask> {
    workerMaxHeapSize.set("512m")
}
```

**Comment by jeremymailen** [comment] 2021-08-12 06:19
I believe there's a memory leak in the underlying ktlint library and then the gradle daemon's memory is eventually exhausted.
You notice it more/faster in the format task because it runs over all files rather than incrementally only on changed files like the lint task does.
I was trying to spot where it could be based on commits in ktlint. It's hard to tell. The `kotlinPsiFileFactory` is a resource that requires careful management.

**Comment by Tapchicoma** [comment] 2021-09-02 14:15
@BraisGabin probably sharing heap dump may help. I still suspect problem in KtLint -> Internal Kotlin version

**Comment by davidburstromspotify** [comment] 2021-09-02 14:23
@Tapchicoma I cannot share the whole heap dump, but did you find anything based off of my screenshot?

**Comment by jeremymailen** [comment] 2021-09-02 20:37
I had been scouting for possible commits in ktlint between 0.40.0 and 0.41.0 that may have been the causes.
There are two I suspect might be relevant, but I can't be certain:
https://github.com/pinterest/ktlint/pull/1088/files
https://github.com/pinterest/ktlint/commit/1bf0d2ed8f4b3dabbde33c648ed701dca55f9ddc

Possibly an closure approach can make sure the factory is always released (with a finally block wrapped around the block
```kotlin
withPsiFileFactory { psiFileFactory ->
  // some linting code
}
```

The other possibility is that the reference counting approach isn't accounting for all situations?

**Comment by gabrielle-cozart** [comment] 2021-09-29 17:12
I have run into the same issue as well. Even changing the following to `4096m` is still failing. I had to remove my ktlint pre-push hook to be able to push to my project. 
```
tasks.withType<org.jlleitschuh.gradle.ktlint.tasks.BaseKtLintCheckTask> {
    workerMaxHeapSize.set("512m")
}
```

**Comment by breispeloton** [comment] 2021-12-15 19:45
Just an FYI for anyone seeing this that this may have been fixed in ktlint 0.43.0. See https://github.com/pinterest/ktlint/issues/1216 and the kotlinter-gradle issue.

**Comment by gabrielle-cozart** [comment] 2021-12-15 20:23
@breispeloton Thanks! I will check this out

**Comment by BraisGabin** [comment] 2021-12-15 20:46
I can't reproduce this issue anymore. @gabrielittner if you can confirm it too I can close the issue. @breispeloton thanks for the heads up!

**Comment by flgubler-ergon** [comment] 2021-12-16 08:46
Can also confirm: Explicitly setting the ktlint-version to 0.43.0 seems to have solved the problem for me as well.

```
ktlint {
  version = "0.43.0"
}
```

**Closed** 2021-12-16 09:00 UTC
Labels: bug

**Comment by gabrielle-cozart** [comment] 2022-01-06 21:51
Okay, so I've been running with version 0.43.0 since this was last updated, and I again got the same error:

```
> Task :app:runKtlintFormatOverMainSourceSet FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:runKtlintFormatOverMainSourceSet'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
   > Java heap space
```

**Comment by JLLeitschuh** [comment] 2022-01-08 04:09
Can you open a new issue? Also, can you provide additional information? 

For example, a build scan link would be helpful, version of the plugin you are using, Gradle version, Ktlint version, ect...
