### ISSUE TITLE
Version 10.0.0 Incompatible with Java-only projects

### ISSUE THREAD

**Issue by DanySK** [JLLeitschuh/ktlint-gradle#467] opened 2021-04-12 10:44 UTC
Hi,
I use ktlint in Gradle Java projects to check for the correctness of the build file. Version 10.0.0 fails as follows though:

```
❯ ./gradlew check --stacktrace
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on

> Configure project :
No username configured for MavenCentral at https://oss.sonatype.org/service/local/staging/deploy/maven2/.

FAILURE: Build failed with an exception.

* What went wrong:
org/jetbrains/kotlin/konan/file/File

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NoClassDefFoundError: org/jetbrains/kotlin/konan/file/File
        at org.jlleitschuh.gradle.ktlint.tasks.GenerateReportsTask$reportsOutputDirectory$1.transform(GenerateReportsTask.kt:100)
        at org.jlleitschuh.gradle.ktlint.tasks.GenerateReportsTask$reportsOutputDirectory$1.transform(GenerateReportsTask.kt:35)
        at org.gradle.api.internal.provider.FlatMapProvider.doMapValue(FlatMapProvider.java:54)
        at org.gradle.api.internal.provider.FlatMapProvider.calculateOwnValue(FlatMapProvider.java:50)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
        at org.gradle.api.internal.provider.MappingProvider.calculateOwnValue(MappingProvider.java:55)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
        at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:128)
        at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:25)
        at org.gradle.api.internal.provider.AbstractProperty.doCalculateValue(AbstractProperty.java:133)
        at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValueNoProducer(AbstractProperty.java:121)
        at org.gradle.api.internal.file.DefaultFilePropertyFactory$AbstractFileVar.access$100(DefaultFilePropertyFactory.java:180)
        at org.gradle.api.internal.file.DefaultFilePropertyFactory$AbstractFileVar$2.calculateOwnValue(DefaultFilePropertyFactory.java:263)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.getOrNull(AbstractMinimalProvider.java:93)
        at org.gradle.api.internal.tasks.properties.FileParameterUtils.resolveOutputFilePropertySpecs(FileParameterUtils.java:116)
        at org.gradle.execution.plan.LocalTaskNode$1.lambda$visitOutputFileProperty$1(LocalTaskNode.java:201)
        at org.gradle.execution.plan.LocalTaskNode.withDeadlockHandling(LocalTaskNode.java:267)
        at org.gradle.execution.plan.LocalTaskNode.access$000(LocalTaskNode.java:48)
        at org.gradle.execution.plan.LocalTaskNode$1.visitOutputFileProperty(LocalTaskNode.java:197)
        at org.gradle.api.internal.tasks.properties.annotations.AbstractOutputPropertyAnnotationHandler.visitPropertyValue(AbstractOutputPropertyAnnotationHandler.java:50)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode.visitProperties(AbstractNestedRuntimeBeanNode.java:56)
        at org.gradle.api.internal.tasks.properties.bean.RootRuntimeBeanNode.visitNode(RootRuntimeBeanNode.java:32)
        at org.gradle.api.internal.tasks.properties.DefaultPropertyWalker.visitProperties(DefaultPropertyWalker.java:41)
        at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:44)
        at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:34)
        at org.gradle.execution.plan.LocalTaskNode.resolveMutations(LocalTaskNode.java:194)
        at org.gradle.execution.plan.DefaultExecutionPlan.getResolvedMutationInfo(DefaultExecutionPlan.java:626)
        at org.gradle.execution.plan.DefaultExecutionPlan.selectNext(DefaultExecutionPlan.java:554)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$executeNextNode$1(DefaultPlanExecutor.java:166)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:155)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)


* Get more help at https://help.gradle.org

BUILD FAILED in 453ms
7 actionable tasks: 7 up-to-date
```

I believe the issue has been fixed, as [this import](https://github.com/JLLeitschuh/ktlint-gradle/blob/44220169b3aba93644e4305084d5573dc970769a/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/GenerateReportsTask.kt#L20) has been removed, but I need a new version to be released.
Is there any release programmed soon?

Thanks

**Comment by Tapchicoma** [comment] 2021-04-12 17:36
Duplicate of #443 

Unfortunately no ETA for the next release.

**Closed by Tapchicoma** 2021-04-12 17:36 UTC
