### ISSUE TITLE
[6.3.0] - Could not find net.swiftzer.semver:semver:1.1.0.

### ISSUE THREAD

**Issue by jaredsburrows** [JLLeitschuh/ktlint-gradle#177] opened 2018-11-27 02:48 UTC
## Project:
https://github.com/jaredsburrows/android-gif-example

## Error:
```
$ gradlew dependencyUpdates

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android-gif-example'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find net.swiftzer.semver:semver:1.1.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/net/swiftzer/semver/semver/1.1.0/semver-1.1.0.pom
       - https://dl.google.com/dl/android/maven2/net/swiftzer/semver/semver/1.1.0/semver-1.1.0.jar
       - https://plugins.gradle.org/m2/net/swiftzer/semver/semver/1.1.0/semver-1.1.0.pom
     Required by:
         project : > org.jlleitschuh.gradle:ktlint-gradle:6.3.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
```

**Comment by JLLeitschuh** [comment] 2018-11-27 02:50
Duplicate of https://github.com/JLLeitschuh/ktlint-gradle/issues/162

**Closed by JLLeitschuh** 2018-11-27 02:50 UTC
