### ISSUE TITLE
addKtlintCheckGitPreCommitHook doens't work if project is inside folder

### ISSUE THREAD

**Issue by IvanShafran** [JLLeitschuh/ktlint-gradle#314] opened 2019-12-13 14:34 UTC
Hi!

I tried to use the git hook task from the plugin, but unfortunately, the plugin doesn't add this task to the project. (addKtlintCheckGitPreCommitHook)
In my scenario, an Android project is placed in a folder that differs from the git root folder.

For example:

folder_a
--.git
--folder_b
----app
------build.gradle
------...
----build.gradle
----...

It happens because of plugin checks for ".git" file in the root project folder (folder_b).
https://github.com/JLLeitschuh/ktlint-gradle/blob/4c0729e50589efb196e0e70b2f4d8e20e05c5995/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt#L62
https://github.com/JLLeitschuh/ktlint-gradle/blob/4c0729e50589efb196e0e70b2f4d8e20e05c5995/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/GitHook.kt#L63

Is it okay If I create PR for this issue fix? Do you have rules for contribution?

Thank you!

**Comment by Tapchicoma** [comment] 2019-12-14 08:25
Duplicate of #284

**Closed by Tapchicoma** 2019-12-14 08:25 UTC
