### ISSUE TITLE
editorconfig changes have no effect

### ISSUE THREAD

**Issue by lolo-io** [JLLeitschuh/ktlint-gradle#463] opened 2021-04-01 11:58 UTC
Hi, 
It seems to me that .editorconfig changes have no effects.

Steps

- Init a new .editorconfig with rules that should make ktlint check fail eg. add indent_size = 2
- run ktlintCheck => build fails : Unexpected indentation (4) (should be 2)
- Put proper value in .editorconfig :  indent_size = 4
- Run ktlintCheck

Result
build fails : Unexpected indentation (4) (should be 2)

Expected results
build is successful

environment :
Android Studio, 
I imported ktlint in build.gradle with new plugin syntax : 

    plugins {
        id "org.jlleitschuh.gradle.ktlint" version "9.4.1"
    }

    subprojects {
        apply plugin : "org.jlleitschuh.gradle.ktlint"

        repositories {
            // Required to download KtLint
            mavenCentral()
        }
    }

This is the same behavior as mentioned in a previously fixed issue : #209

Invalidate cache and restart doesn't change anything.
Deleting .editorconfig will make ktlint not use the old file anymore, but creating a new one with new values will result in ktlint resusing old .editorconfig config.

The new .editorconfig config is randomly applied after minutes of rebuild, cache reset. Can't find a way to always take new changes into account.

Edit:
Downgrading to 9.4.1 works for me, so this is an issue of 10.0.0. 
I'll use this workaround for now. (Switching back to 10.0.0 still keeps old config)

**Comment by agile-jordi** [comment] 2021-04-03 23:57
+1
As a workaround, when modifying any gradle build file, it properly recognizes changes to .editorconfig.

**Comment by Tapchicoma** [comment] 2021-04-06 10:00
Duplicate of #456

**Closed by Tapchicoma** 2021-04-06 10:00 UTC
