### ISSUE TITLE
Missing dependencies between tasks

### ISSUE THREAD

**Issue by asarkar** [JLLeitschuh/ktlint-gradle#500] opened 2021-06-12 00:48 UTC
```
15
> Task :runKtlintFormatOverKotlinScripts
16
Execution optimizations have been disabled for task ':runKtlintFormatOverKotlinScripts' to ensure correctness due to the following reasons:
17
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test'. Reason: Task ':ktlintKotlinScriptCheck' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
18
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test'. Reason: Task ':ktlintMainSourceSetCheck' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
19
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test'. Reason: Task ':ktlintTestSourceSetCheck' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
20
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test'. Reason: Task ':runKtlintCheckOverKotlinScripts' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
21
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test'. Reason: Task ':runKtlintCheckOverMainSourceSet' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
22
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test'. Reason: Task ':runKtlintCheckOverTestSourceSet' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
23

24
> Task :ktlintKotlinScriptFormat
25

26
> Task :runKtlintFormatOverMainSourceSet
27
Execution optimizations have been disabled for task ':runKtlintFormatOverMainSourceSet' to ensure correctness due to the following reasons:
28
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test/build/intermediates/ktLint/reporters.bin'. Reason: Task ':runKtlintFormatOverMainSourceSet' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
29
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test/src/main/java'. Reason: Task ':runKtlintCheckOverMainSourceSet' uses this output of task ':runKtlintFormatOverMainSourceSet' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
30
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test/src/main/java'. Reason: Task ':runKtlintFormatOverMainSourceSet' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
31
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test/src/main/kotlin'. Reason: Task ':runKtlintCheckOverMainSourceSet' uses this output of task ':runKtlintFormatOverMainSourceSet' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
32
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test/src/main/kotlin'. Reason: Task ':runKtlintFormatOverMainSourceSet' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
33

34
> Task :runKtlintFormatOverTestSourceSet
35
Execution optimizations have been disabled for task ':runKtlintFormatOverTestSourceSet' to ensure correctness due to the following reasons:
36
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test/build/intermediates/ktLint/reporters.bin'. Reason: Task ':runKtlintFormatOverTestSourceSet' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
37
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test/src/test/java'. Reason: Task ':runKtlintCheckOverTestSourceSet' uses this output of task ':runKtlintFormatOverTestSourceSet' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
38
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test/src/test/java'. Reason: Task ':runKtlintFormatOverTestSourceSet' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
39
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test/src/test/kotlin'. Reason: Task ':runKtlintCheckOverTestSourceSet' uses this output of task ':runKtlintFormatOverTestSourceSet' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
40
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test/src/test/kotlin'. Reason: Task ':runKtlintFormatOverTestSourceSet' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
41

42
> Task :ktlintMainSourceSetFormat
43
Execution optimizations have been disabled for task ':ktlintMainSourceSetFormat' to ensure correctness due to the following reasons:
44
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test/build/intermediates/ktLint/reporterProviders.bin'. Reason: Task ':ktlintMainSourceSetFormat' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
45
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test/build/intermediates/ktLint/reporters.bin'. Reason: Task ':ktlintMainSourceSetFormat' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
46
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test/build/intermediates/ktLint/runKtlintFormatOverMainSourceSet_errors.bin'. Reason: Task ':ktlintMainSourceSetFormat' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
47

48
> Task :ktlintTestSourceSetFormat
49
Execution optimizations have been disabled for task ':ktlintTestSourceSetFormat' to ensure correctness due to the following reasons:
50
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test/build/intermediates/ktLint/reporterProviders.bin'. Reason: Task ':ktlintTestSourceSetFormat' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
51
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test/build/intermediates/ktLint/reporters.bin'. Reason: Task ':ktlintTestSourceSetFormat' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
52
  - Gradle detected a problem with the following location: '/home/runner/work/grpc-test/grpc-test/build/intermediates/ktLint/runKtlintFormatOverTestSourceSet_errors.bin'. Reason: Task ':ktlintTestSourceSetFormat' uses this output of task ':runKtlintFormatOverKotlinScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

https://docs.gradle.org/7.0.1/release-notes.html#build-reliability

> Validate missing dependencies between tasks
>
> One of the potential problems now flagged is a task that consumes the output produced by another without declaring an explicit or inferred task dependency. Gradle now detects the missing dependency between the consumer and the producer and emits a warning in that case. For more information see the user manual on input and output validation.

**Comment by Tapchicoma** [comment] 2021-06-15 21:02
Duplicate of #457

**Closed by Tapchicoma** 2021-06-15 21:02 UTC
