### ISSUE TITLE
Android: `ktlint[SourceSetName]SourceSetCheck` task doesn't take kotlin `srcDir` into account

### ISSUE THREAD

**Issue by StefMa** [JLLeitschuh/ktlint-gradle#702] opened 2023-08-15 14:45 UTC
### Given:
Apply the plugin to an android project.
The android project does have a `main/src/kotlin` directory.
If you now run `ktlintMainSourceSetCheck` it will not run over this directory and therefore does not lint.

### Temporary solutions I found so far: 
* Move the source code to `src/main/java`.
* Add this code:
```kotlin
android.sourceSets.maybeCreate("main").java.srcDir("src/main/kotlin")
```

### Why isn't this working?
I guess (not 100% sure) I found the line in question:

https://github.com/JLLeitschuh/ktlint-gradle/blob/e5e60381f88f3eba9f3cc2904b7ae4a00b83d7da/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/android/AndroidPluginsApplier.kt#L70-L72

I guess this one will only create the expected task for the `sourceSet.java` source directories, but **not** for the `sourceSet.kotlin` source directories.

As you can see here, the [java property](https://developer.android.com/reference/tools/gradle-api/8.0/com/android/build/api/dsl/AndroidSourceSet#java()) is different to the [kotlin property](https://developer.android.com/reference/tools/gradle-api/8.0/com/android/build/api/dsl/AndroidSourceSet#kotlin()).

That would also explain why it would work when we add the kotlin (`src/main/kotlin`) `srcDir` to the `java` property.

If this is the case, a fix would be quite easy:
```diff
- val androidSourceSet = sourceSet.java as DefaultAndroidSourceDirectorySet
+ val androidSourceSet = sourceSet.kotlin as DefaultAndroidSourceDirectorySet
```

### Why would it solve it?
Because the `kotlin` property contains already the `main/src/java` source directory.

You can check this by running:
```groovy
android.sourceSets.all {
    println("Java -->" + (it.java as DefaultAndroidSourceDirectorySet).srcDirs)
}

android.sourceSets.all {
    println("Kotlin -->" + (it.kotlin as DefaultAndroidSourceDirectorySet).srcDirs)
}
```

This will print out something like:
```shell
Jaava -->[/Users/stefan/Developer/Android/[project]/[path]/lib-[something]/src/androidTest/java]
Jaava -->[/Users/stefan/Developer/Android/[project]/[path]/lib-[something]/src/androidTestDebug/java]
Jaava -->[/Users/stefan/Developer/Android/[project]/[path]/lib-[something]/src/androidTestRelease/java]
Jaava -->[/Users/stefan/Developer/Android/[project]/[path]/lib-[something]/src/debug/java]
Jaava -->[/Users/stefan/Developer/Android/[project]/[path]/lib-[something]/src/main/java]

Kotlin -->[/Users/stefan/Developer/Android/[project]/[path]/lib-[something]/src/androidTest/kotlin, /Users/stefan/Developer/Android/[project]/[path]/lib-[something]/src/androidTest/java]
Kotlin -->[/Users/stefan/Developer/Android/[project]/[path]/lib-[something]/src/androidTestDebug/kotlin, /Users/stefan/Developer/Android/[project]/[path]/lib-[something]/src/androidTestDebug/java]
Kotlin -->[/Users/stefan/Developer/Android/[project]/[path]/lib-[something]/src/androidTestRelease/kotlin, /Users/stefan/Developer/Android/[project]/[path]/lib-[something]/src/androidTestRelease/java]
Kotlin -->[/Users/stefan/Developer/Android/[project]/[path]/lib-[something]/src/debug/kotlin, /Users/stefan/Developer/Android/[project]/[path]/lib-[something]/src/debug/java]
Kotlin -->[/Users/stefan/Developer/Android/[project]/[path]/lib-[something]/src/main/kotlin, /Users/stefan/Developer/Android/[project]/[path]/lib-[something]/src/main/java]
```

I'm ready to create an PR in case someone of the owners can confirm my assuptions 🙃

**Comment by mtrakal** [comment] 2023-08-17 22:57
I've same issue, but with just run `./gradlew ktlint` on `src/main/kotlin/` folders. 
It ignores them all the time without me knowing about it, until I migrate the whole codebase onto trailing comma, and only `src/main/java/` files were changed and validated.

Workaround: dd this to build.gradle.kts file:

```
sourceSets {
        getByName("main").java.srcDirs("src/main/kotlin/")
```

but why it is required to add as `.java.` and not as `.kotlin.` or why didn't work:
```
allprojects {
    ktlint {
        filter {
            include("**/kotlin/**")
        }
    }
}
```
I have no idea. But the code above works for me.

**Comment by JLLeitschuh** [comment] 2023-08-18 00:22
What versions of Gradle are you running? Was this always an issue, or is this only broken due to an update?

**Comment by StefMa** [comment] 2023-08-18 07:04
> but why it is required to add as `.java.` and not as `.kotlin.` or why didn't work:
> 
> ```
> allprojects {
>     ktlint {
>         filter {
>             include("**/kotlin/**")
>         }
>     }
> }
> ```

If my assumption is correct, than this is already too late.
Your filter doesn't include the `src/main/kotlin` filter, instead it searches for `**/kotlin/**` **within** the `src/main/java` directory.
So in case you would have `src/main/java/kotlin` it would work. But this would obviously clash with your package 😁 

> What versions of Gradle are you running? Was this always an issue, or is this only broken due to an update?

Gradle: 8.2
AGP: 8.0.2
ktlint-gradle: 11.3.1 (maybe we should upgrade 😁, wonder why dependabot doesn't catch this yet 🤔 ) however, didn't work with 11.5.1 too.

Unfourtnaly I can't say if this was always an issue.
In the past we always had `java` directories. As we have a big multi-project build we have only a handfull of modules that have an `kotlin` dir (instead of `java`). We assumed that it workes there.
But all of the sudden we found out that this is not the case. So I land here 😁

**Comment by StefMa** [comment] 2023-08-18 07:13
Just did another observation that might be relevant:
This is *only* an Android issue.
If I have an "normal" Kotlin project (applying only the kotlin-jvm plugin, not the Android Gradle plugin), the `src/main/kotlin` dir will be checked correctly.

**Comment by mtrakal** [comment] 2023-08-18 20:05
I can confirm, that I use it in android project too. We started migrate to kotlin folders just few weeks ago, because android studio start supporting kotlin folders in short history natively without specifying it in source set. Before we had all kotlin code in java folders. So before it was not issue for us. But later we recognise, that some code is not checked / formatted.
Gradle 8.2.1

**Comment by StefMa** [comment] 2023-08-19 19:23
I just made the required changes, tested it in our project and created a [PR here](https://github.com/JLLeitschuh/ktlint-gradle/pull/703).

@mtrakal if you want you can test it on your side as well and report if it works for you 🙂 An detailed explanation how to can be found in the PR.

**Comment by wakingrufus** [comment] 2023-08-19 20:32
Thanks! Ill take a look at this on monday

**Comment by wakingrufus** [comment] 2023-10-23 11:32
Hi, I have been working on fixing some bugs. I think we are almost in a good spot with that. after that, I will work on the removal of Gradle 6 support. After that, I think we will be good to merge the AGP related change in #703

**Comment by sebi-ursulescu** [comment] 2023-12-15 02:07
I struggled with this today and tried to find a quick fix for it and I made it work by adding this in our KtlintConventionPlugin.
Basically I'm searching for the corresponding source set of the ktlint task and I'm setting the source to the kotlin one.
It's a small hack with the hardcoded text, but I couldn't find a more dynamic way. Hope it will get fixed soon so we could remove this.

```
tasks.withType<BaseKtLintCheckTask> {
    if (inputs.sourceFiles.isEmpty) {
        val sourceSet = kotlinExtension.sourceSets.first {
            name.endsWith("Over${it.name}SourceSet", ignoreCase = true)
        }

        setSource(sourceSet.kotlin.sourceDirectories)
    }
}
```

**Comment by wakingrufus** [comment] 2023-12-20 19:53
I think I finally have a fix for this: 
https://github.com/JLLeitschuh/ktlint-gradle/pull/733
I'll try to get this released before Christmas :santa:

**Closed** 2024-01-09 05:31 UTC
