### ISSUE TITLE
EditorConfig insert_final_newline has no effect

### ISSUE THREAD

**Issue by khongi** [JLLeitschuh/ktlint-gradle#462] opened 2021-03-30 21:28 UTC
While .editorconfig `insert_final_newline = true` is set `ktlintCheck` still reports files that has final new line.

What it reports:
`Redundant newline (\n) at the end of file`

On version 9.4.1 it works as expected.

**Comment by Tapchicoma** [comment] 2021-04-06 10:00
Duplicate of #456

**Closed by Tapchicoma** 2021-04-06 10:00 UTC
