### ISSUE TITLE
Could not determine the dependencies of task ':ktlintKotlinScriptCheck'.

### ISSUE THREAD

**Issue by pdb-stripe** [JLLeitschuh/ktlint-gradle#714] opened 2023-09-27 16:53 UTC
After upgrading from ktlint 0.50.0 to 1.0.0, and using the latest Gradle plugin (11.6.0), I get the following error:

```
Could not determine the dependencies of task ':ktlintKotlinScriptCheck'.
> Could not resolve all task dependencies for configuration ':ktlintReporter'.
   > Could not resolve io.github.oshai:kotlin-logging:5.1.0.
     Required by:
         project :
      > Cannot choose between the following variants of io.github.oshai:kotlin-logging:5.1.0:
          - debugRuntimeElements-published
          - jvmRuntimeElements-published
          - releaseRuntimeElements-published
        All of them match the consumer attributes:
          - Variant 'debugRuntimeElements-published' capability io.github.oshai:kotlin-logging:5.1.0:
              - Unmatched attributes:
                  - Provides com.android.build.api.attributes.BuildTypeAttr 'debug' but the consumer didn't ask for it
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
                  - Provides org.jetbrains.kotlin.platform.type 'androidJvm' but the consumer didn't ask for it
          - Variant 'jvmRuntimeElements-published' capability io.github.oshai:kotlin-logging:5.1.0:
              - Unmatched attributes:
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
                  - Provides org.jetbrains.kotlin.platform.type 'jvm' but the consumer didn't ask for it
          - Variant 'releaseRuntimeElements-published' capability io.github.oshai:kotlin-logging:5.1.0:
              - Unmatched attributes:
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
                  - Provides org.jetbrains.kotlin.platform.type 'androidJvm' but the consumer didn't ask for it
   > Could not resolve io.github.oshai:kotlin-logging:5.1.0.
     Required by:
         project :
      > Cannot choose between the following variants of io.github.oshai:kotlin-logging:5.1.0:
          - debugRuntimeElements-published
          - jvmRuntimeElements-published
          - releaseRuntimeElements-published
        All of them match the consumer attributes:
          - Variant 'debugRuntimeElements-published' capability io.github.oshai:kotlin-logging:5.1.0:
              - Unmatched attributes:
                  - Provides com.android.build.api.attributes.BuildTypeAttr 'debug' but the consumer didn't ask for it
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
                  - Provides org.jetbrains.kotlin.platform.type 'androidJvm' but the consumer didn't ask for it
          - Variant 'jvmRuntimeElements-published' capability io.github.oshai:kotlin-logging:5.1.0:
              - Unmatched attributes:
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
                  - Provides org.jetbrains.kotlin.platform.type 'jvm' but the consumer didn't ask for it
          - Variant 'releaseRuntimeElements-published' capability io.github.oshai:kotlin-logging:5.1.0:
              - Unmatched attributes:
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
                  - Provides org.jetbrains.kotlin.platform.type 'androidJvm' but the consumer didn't ask for it

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

I tried adding it to my classpath dependencies, but it resulted in the same behavior.

**Comment by wakingrufus** [comment] 2023-09-27 17:42
What version of gradle are you using?

**Comment by pdb-stripe** [comment] 2023-09-27 21:14
> What version of gradle are you using?

7.6.2

**Comment by angelorohit** [comment] 2023-10-03 18:58
I'm facing the same issue. I'm on Gradle version 7.4.2. The issue only occurs when I bump the ktlint version from `0.50.0` to `1.0.0`. The issue doesn't occur when I simply bump the Gradle plugin to `org.jlleitschuh.gradle:ktlint-gradle:11.6.0`.

**Comment by Xinkle** [comment] 2023-10-11 01:19
https://mvnrepository.com/search?q=io.github.oshai%3Akotlin-logging

there is no `io.github.oshai:kotlin-logging:5.1.0`. only `io.github.oshai:kotlin-logging-jvm:5.1.0`. am i see wrong repository?

**Comment by wakingrufus** [comment] 2023-10-23 11:26
I have having trouble reproducing this. can you try adding 
```
configurations.named("ktlint"){
    attributes {
        attribute(Attribute.of("org.jetbrains.kotlin.platform.type", KotlinPlatformType::class.java),KotlinPlatformType.jvm)
    }
}
```
to your buildscript to see if it solves the issue? if this works, I can build it in to the plugin
Thanks.

**Comment by pdb-stripe** [comment] 2023-10-23 15:47
My observations:

1. This is simplest to reproduce when applying ktlint to the buildSrc module, since it is evaluated first, and it fails during Gradle configuration time.
2. The above code snippet gets past the configuration error in buildSrc, but results in another error (below).
3. When running `./gradlew ktlintCheck`, and even with ktlint removed from buildSrc, the code snippet above does not fix the issue.

Here is the error I noticed in buildSrc (does buildSrc honor the .editorconfig at the repository root?):

```
Caused by: java.lang.IllegalStateException: Skipping rule(s) which are depending on a rule which is not loaded. Please check if you need to add additional rule sets before creating an issue.
  - Rule with id 'RuleId(value=standard:string-template-indent)' requires rule with id 'RuleId(value=standard:indent)' to be loaded
	at com.pinterest.ktlint.rule.engine.internal.rulefilter.RunAfterRuleFilter.filter(RunAfterRuleFilter.kt:77)
Caused by: java.lang.IllegalStateException: Skipping rule(s) which are depending on a rule which is not loaded. Please check if you need to add additional rule sets before creating an issue.

	at com.pinterest.ktlint.rule.engine.internal.rulefilter.RuleFilterKt.applyRuleFilters(RuleFilter.kt:15)
	at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$Companion.createRuleExecutionContext$ktlint_rule_engine(RuleExecutionContext.kt:192)
	at com.pinterest.ktlint.rule.engine.api.KtLintRuleEngine.lint(KtLintRuleEngine.kt:94)
	at org.jlleitschuh.gradle.ktlint.worker.KtLintInvocation100.invokeLint(KtLintInvocation100.kt:47)
	at org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction.execute(KtLintWorkAction.kt:123)
	... 22 more
```

**Comment by pdb-stripe** [comment] 2023-12-11 15:55
Although not a solution, I have worked around this issue by upgrading tools to 

Gradle 8.5
Ktlint 1.0.1
AGP 8.1.4
Ktlint-Gradle 12.0.2

**Comment by wakingrufus** [comment] 2023-12-11 17:13
to give more insight, the root cause of this is that in newer ktlint versions, ktlint has a dependency on `io.github.oshai:kotlin-logging`. This library publishes variants, so Gradle needs variant information to select the right one. this _should_ be handled in gradle 7.6+ automatically though. maybe it is a KGP or AGP issue.

**Comment by wakingrufus** [comment] 2023-12-22 16:01
I have confirmed that old KGP and AGP plugins _can_ also cause this issue, as well as old Gradle versions. closing for now unless it happens again while using up to date plugins

**Closed by wakingrufus** 2023-12-22 16:01 UTC
