### ISSUE TITLE
Skip lint if a filename contains the blank space character

### ISSUE THREAD

**Issue by Starmel** [JLLeitschuh/ktlint-gradle#373] opened 2020-07-29 15:31 UTC
Task `ktlintFormat` skipping check files which a filename contains blank space character. The command line ktlint app (`brew install ktlint`) handle thats files correct.

Caught bug for the name `AsyncResult + Rx`. `AsyncResult+Rx` works success 

Gradle task output: 

<details>
<summary>Details</summary>

```bash
18:19:35: Executing task 'ktlintFormat'...


> Configure project :
Kotlin Multiplatform Projects are an experimental feature.
null
No credential for Artifact deploy

> Task :ktlintAndroidMainSourceSetFormat
> Task :ktlintAndroidTestSourceSetFormat UP-TO-DATE
> Task :ktlintCommonMainSourceSetFormat UP-TO-DATE
> Task :ktlintCommonTestSourceSetFormat NO-SOURCE
> Task :ktlintIosArm32MainSourceSetFormat NO-SOURCE
> Task :ktlintIosArm32TestSourceSetFormat NO-SOURCE
> Task :ktlintIosArm64MainSourceSetFormat NO-SOURCE
> Task :ktlintIosArm64TestSourceSetFormat NO-SOURCE
> Task :ktlintIosMainSourceSetFormat UP-TO-DATE
> Task :ktlintIosTestSourceSetFormat NO-SOURCE
> Task :ktlintKotlinScriptFormat NO-SOURCE
> Task :ktlintFormat

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
4 actionable tasks: 1 executed, 3 up-to-date
18:19:36: Task execution finished 'ktlintFormat'.
```

</details>

Command line app output:

<details>
<summary>Details</summary>

```bash
$ ktlint
/Users/admin/Dev/os/Project-name/src/androidMain/kotlin/ru/company/mobile/shared/core/async_result/AsyncResult + Rx.kt:5:1: Unused import
/Users/admin/Dev/os/Project-name/src/androidMain/kotlin/ru/company/mobile/shared/core/async_result/AsyncResult + Rx.kt:7:1: Needless blank line(s)
/Users/admin/Dev/os/Project-name/src/androidMain/kotlin/ru/company/mobile/shared/core/async_result/AsyncResult + Rx.kt:37:1: Needless blank line(s)
```

</details>

Gradle settings:

<details>
<summary>Details</summary>

```groovy
id "org.jlleitschuh.gradle.ktlint" version "9.3.0"

ktlint {
    outputColorName = "RED"
    disabledRules = ["final-newline", "no-wildcard-imports"]
}
```

</details>

**Comment by Tapchicoma** [comment] 2020-09-02 11:56
Duplicate of #362.

**Closed by Tapchicoma** 2020-09-02 11:56 UTC
